### ISSUE TITLE
loadDiscreteData function is extremely slow when 'alarm dataset' (20000 samples) used

### ISSUE THREAD

**Issue by yasu-sh** [bd2kccd/r-causal#106]
I am using alarm dataset of bnlearn and the synthetic discrete data, which has 20000 samples.
The reading time is about 60secs and causal discovery time is about 2-3 secs. 

![image](https://user-images.githubusercontent.com/89838961/195258734-517af3fa-acc6-44a2-8815-f417dab33363.png)

I feel like to improve the time consuming situation and ideas:
1. Not using sapply at entire sample sizes, but factor function can be used.
2. Reduces on-site memory read-write. matrix object is used for batch data conversion.
3. Avoids using '$' character and Uses .jcall function since this reflect method is time consuming.
4. Disables console output 

it would be making good result.

**Comment by jdramsey** [comment]
BTW I'm pretty sure this will be much faster using py-tetrad in R...

**Comment by yasu-sh** [comment]
@jdramsey Yes! This issue was already solved by my pull-request last year.

The selection of R's implementation is important since the performance changes a lot. 
R has lazy evaluation and we need to check where is hot-spots.
https://github.com/bd2kccd/r-causal/blob/fc370245e938d5a2cb6e6abd4548bf7107fdd1dc/R/tetrad_utils.R#L336

**Comment by jdramsey** [comment]
Ah, thanks!
