### ISSUE TITLE
GFCI <- include this one too!

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/r-causal#11]
Just read Jiji Zhang's dissertation. Please include GFCI in future iterations as well, since it models hidden latent variables, which may be very important with messy clinical data derived (through several steps that could potentially introduce noise) from electronic health records. 
Thanks!
 -S

**Comment by chirayukong** [comment]
I'll add it then.

**Comment by chirayukong** [comment]
Scott, here, it is. Feel free to try GFCI. :-)

**Comment by kingfish777** [comment]
Cool! Will try this evening.

**Comment by kingfish777** [comment]
I have attached my script with data. GFCI hangs. I have to kill -9 the process as it was hanging all night. Please advise! -S
[Ibuprofen.zip](https://github.com/bd2kccd/r-causal/files/409486/Ibuprofen.zip)
