### ISSUE TITLE
Prior knowledge not working correctly, at least with FGS discrete

### ISSUE THREAD

**Issue by lizziesilver** [bd2kccd/r-causal#18]
We got a CCD Helpdesk query about prior knowledge. To answer it I created a worked example, and I found a bug: When my Prior Knowledge includes just some prior edges, it prevents FGS discrete from creating any _other_ edges.

Here's the example. First load the library and data:
```
library(rcausal)
data("sim_discrete_data_20vars_100cases")
```
Run FGS discrete with NO prior knowledge:
```
fgs_agnostic <- fgs.discrete(df = sim_discrete_data_20vars_100cases)
```
Look at the output:
```
> fgs_agnostic$edges
[1] "X3 --- X7"   "X9 --- X3"   "X10 --- X4"  "X15 --> X19" "X18 --- X14" 
[6] "X11 --- X14" "X14 --- X16" "X17 --> X19" "X13 --- X6"  "X13 --- X7" 
```
Now try requiring two of those edges by prior knowledge. Because FGS was able to discover those edges even _without_ prior knowledge, requiring them should not change the output at all.
```
known_edges <- list()
known_edges[[1]] <- c("X15", "X19")
known_edges[[2]] <- c("X17", "X19")

fgs_with_knowledge <- fgs.discrete(df = sim_discrete_data_20vars_100cases, 
                                   priorKnowledge = priorKnowledge(forbiddirect = NULL, 
                                                                   requiredirect = known_edges, 
                                                                   addtemporal = NULL))
```
Look at the output:
```
> fgs_with_knowledge$edges
[1] "X17 --> X19" "X15 --> X19"
```
***FGS only learns the two edges that were required in the prior knowledge.***

I get the same result when instead of passing knowledge as a list, I use a knowledge file with the following text:
```
/knowledge
addtemporal

forbiddirect

requiredirect
X15 X19
X17 X19
```
I am using the most current version of R (3.3.1), rcausal, Java, and rJava. I checked that rJava is accessing the most current version of Java:
```
> .jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
[1] "1.8.0_101-b13"
```

**Comment by kingfish777** [comment]
Could you see if this holds true for your example with GFCI as well?

**Comment by chirayukong** [comment]
Very interesting. I tried this issue on causal web and got the same result. Need to engage Joe Ramsey on this issue in the Tetrad-Lib repo.

**Comment by lizziesilver** [comment]
@kingfish777 : No, the bug doesn't affect GFCI. I also checked whether it affects FGS continuous as well as FGS discrete; it does.

**Comment by chirayukong** [comment]
Prior knowledge issue is fixed.
