### ISSUE TITLE
pcmax bug I just noticed

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/r-causal#31]
Should there be a call to setSignificance in PcMax for pcmax.R:
` .jcall(pcmax_instance, "V", "setSignificance", useSignificance)`
after
` .jcall(pcmax_instance, "V", "setUseHeuristic", useHeuristic)`
If not, significance parameter for users will be lost (set to default). 
 -Scott

**Comment by chirayukong** [comment]
I don't think so, Scott. The significance value is used as a parameter for the independenceTest object. Therefore, no need to set the significance after a useHeuristic parameter.

Kong

P.S. I updated the new jar and source code to the master branch.

**Comment by kingfish777** [comment]
Right, but what if one wishes to set the significance (alpha) to an arbitrarily high or (in my case) low value, say, 0.000005 (where useHeuristic = FALSE)? One would still need to have a way to pass that parameter to PcMax, right?
-Scott

**Comment by chirayukong** [comment]
Scott,

You always need to pass a significance value to the IndependenceTest object as a snippet belows:

`# Data Frame to Independence Test`
`    indTest = NULL`
`    if(continuous){`
`    	tetradData <- loadContinuousData(df)`
`    	indTest <- .jnew("edu/cmu/tetrad/search/IndTestFisherZ", tetradData, significance)`
`    }else{`
`    	tetradData <- loadDiscreteData(df)`
`    	indTest <- .jnew("edu/cmu/tetrad/search/IndTestChiSquare", tetradData, `
`    		significance)`
`    }`.
So does a useHeuristic parameter (which default value is TRUE).

https://github.com/bd2kccd/r-causal/blob/master/R/pcmax.R

**Comment by kingfish777** [comment]
Chirayu:
I got it. Sorry, but this was the first week of exposure with respect to the code sorcery that undergirds the Java/R API, so I am still a bit dense with respect to reading rJava.
In my exercise of wrapping pcmax, I found that it was not very difficult to write the wrappers (I got it working from my local installation). Most exciting is that there is so much more to wrap into r-causal from Tetrad (and that it is feasible without colossal mental effort).
I will install the official version later today or this weekend and provide some feedback with respect to pcmax and fges.
Keep doing the great work!
-Scott

**Comment by kingfish777** [comment]
Hi Chirayu,
I am not certain that the significance value is being passed. I am trying to set the alpha to a 0.000005 level. Also, (unrelated) when I run the latest r-causal on Mac, I am getting a major/minor unsupported 51.0 from the Java. This indicates that there may be a compliance vs runtime inconsistency. I spent the better chunk of this evening un-re-un-re-un-in-re-installing various JDKs and none seem to work.  
 --Scott 
Another question: where is the github repo for lib-tetrad-6.0.1-**snapshot**-tetradcmd? If I had access to that, I could build it locally and drop it into a local r-causal-master to tar.gz up! I only see it in target/jar form here: http://www.phil.cmu.edu/projects/tetrad_download/maven/edu/cmu/tetrad-lib/5.3.0-SNAPSHOT/
Thanks!

**Comment by kingfish777** [comment]
Note the disparity between the significance levels in this run on toy data: 

## ### ```
> > pcmax(df = dat, continuous = FALSE, significance = 0.000005)
> node_names:  drug 
> value: [1] 0 1
> 
> node_names:  ade 
> value: [1] 0 1
> 
> node_names:  c1 
> value: [1] 0 1
> 
> node_names:  c2 
> value: [1] 0 1
> 
> node_names:  u1 
> value: [1] 0 1
> 
> node_names:  u2 
> value: [1] 0 1
> 
> Datasets:
> dat 
> 
> Graph Parameters:
> continuous =  FALSE 
> depth =  -1 
> maxPathLength =  3 
> useHeuristic =  TRUE 
> significance =  0 
> verbose =  FALSE 
> $datasets
> [1] "dat"
> 
> $parameters
> $parameters[[1]]
> NULL
> 
> $parameters$continuous
> [1] FALSE
> 
> $parameters$depth
> [1] -1
> 
> $parameters$maxPathLength
> [1] 3
> 
> $parameters$useHeuristic
> [1] TRUE
> 
> $parameters$significance
> [1] 5e-06
> 
> $parameters$verbose
> [1] FALSE
> 
> 
> $nodes
> [1] "drug" "ade"  "c1"   "c2"   "u1"   "u2"  
> 
> $edges
> list()
> 
> $graphNEL
> A graphNEL graph with directed edges
> Number of Nodes = 6 
> Number of Edges = 0 
> 
> attr(,"class")
> [1] "pcmax"
```

**Comment by chirayukong** [comment]
A major/minor unsupported 51.0 indicates that your JRE version is wrong. The jar file I built was java 7. You can also build the lib-tetrad-6.0.1-snapshot-tetradcmd jar by your own. You need to download the whole tetrad project at https://github.com/cmu-phil/tetrad on the development branch. I don't think there is a repo that hosts the tetrad-lib-cmd jar file.

**Comment by kingfish777** [comment]
Yep. I rebuilt it locally. It is now working. Whew! Now if I could figure out how to tell my MBP not to go to sleep!
 -S

**Comment by kingfish777** [comment]
ok, what I noticed was not really a bug in terms of functionality, but in the console the significance/alpha value is displayed as an integer (0), when I was expecting a 0.000005 or something. 

from r-causal-master/R/pcmax.R:
` cat("significance = ", as.integer(significance), "\n")`

You may close this ticket. Thanks!

**Comment by chirayukong** [comment]
Thanks for a tip on the significance setting.
