### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/r-causal#7]
Do what Harry says!
also: consolidate tetrad-cmd and tetrad.
also: retain and/or import "MULT" pseudocolumn functionality across all versions! 
r-causal is a mess! A delightful one, though. Keep up the good work!
BTW, using igraph package, you can convert graphNEL/RGraphviz objects to igraph objects, which are a lot easier to turn into publishable eye candy, IMHO.
 -S

**Comment by chirayukong** [comment]
And what did Harry say? Anyway, thanks for commenting on this messy r-causal project. I'll create yet another way to create graph with igraph then.

**Comment by kingfish777** [comment]
I'd say that the higher priority should be integrating prior knowledge/fixing addtemporal feature, etc..

The igraph part already has a solution.

________________________________

**Comment by chirayukong** [comment]
Prior knowledge is already there. Is there any problem with it?

**Comment by kingfish777** [comment]
Oh, Harry basically said to synch the functionality of r-causal with the rest of Tetrad, though I realize that that will take a wihle!

In the meantime, for my purposes (since I work with discrete data), it would be great if you could, in order of importance, fix the following: 1.) prior knowledge functionality and 2.) MULT (3. and 4.) estimates from parameterized DAGs from the PAGs) & PC algorithm implementation. 

Yes. I can document problem using prior knowledge from yesterday. And priorknowledgefromfile is definitely not working. This problem having to do with .java("L ... io  libraries and such. This was using r-causal docker (in Ubuntu Linux 16.04) and r-causal in rstudio (on Windows 10 machine with 64g RAM). I can boot those up and drop in the stack trace/error msgs. 

I would like to run r-causal in rstudio on my Linux boxes without the Docker, but rJava is giving me trouble. I can drop those messages in as well, so I can't report back from those environments yet (CentOS and Ubuntu and Mint). 

I will be testing on my MacBP in the coming days as well.

**Comment by chirayukong** [comment]
Thanks for the comment. Sorry for a priorknowledgefromfile function. It was about the rJava calling function. I'm still working on fixing it. Shouldn't push it to the master yet.

**Comment by kingfish777** [comment]
Sys.setenv(JAVA_HOME="")
library(rcausal)
prozac <- read.delim("/Users/kingf/prozac/prozac.txt")    #Load the prozac dataset
setwd("/Users/kingf/prozac")
#Compute FGS search
fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0,samplePrior=1.0, priorKnowledge(addtemporal = c("depressive_symptoms stress alcohol_consumption major_depressive_disorder Fluoxetine depressive_disorder arthralgia aspirin antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal acetaminophen varicosity hemorrhoids fibroid_tumor", "GIB") ),
                             depth = -1, numOfThreads = 6)
# fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0,samplePrior=1.0, 
# depth = -1, faithfulness = TRUE, numOfThreads = 6)
fgs.discrete$parameters #Show the FGS's parameters
fgs.discrete$datasets #Show the dataset
fgs.discrete$nodes #Show the result's nodes
fgs.discrete$edges #Show the result's edges
library(Rgraphviz)
plot(fgs.discrete$graphNEL, attrs=list(node=list(width = 2, height=4, shape = "ellipse", lwd=500, cex=500, lty=100, fillcolor="white", fontsize=70, fontcolor="darkgreen"), 
                                       edge=list(color="lightblue", lwd=1),
                                       graph=list(rankdir="LR"))) 
library(igraph)
iprozac <- igraph.from.graphNEL(fgs.discrete$graphNEL) # convert graphNEL to igraph object
plot(iprozac)

####################  stack trace ##########################


> Sys.setenv(JAVA_HOME="")
> library(rcausal)
> prozac <- read.delim("/Users/kingf/prozac/prozac.txt")    #Load the prozac dataset
> setwd("/Users/kingf/prozac")
> #Compute FGS search
> fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0,samplePrior=1.0, priorKnowledge(addtemporal = c("depressive_symptoms stress alcohol_consumption major_depressive_disorder Fluoxetine depressive_disorder arthralgia aspirin antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal acetaminophen varicosity hemorrhoids fibroid_tumor", "GIB") ),
+                              depth = -1, numOfThreads = 6)
node_names:  depressive_disorder 
value: [1] 0 1

node_names:  depressive_symptoms 
value: [1] 0 1

node_names:  abdominal_pain 
value: [1] 0 1

node_names:  arthralgia 
value: [1] 0 1

node_names:  aspirin 
value: [1] 0 1

node_names:  hemorrhoids 
value: [1] 0 1

node_names:  acetaminophen 
value: [1] 0 1

node_names:  varicosity 
value: [1] 0 1

node_names:  antiHYPHENinflammatory_agentsCOMMA_nonHYPHEN 
value: [1] 0 1

node_names:  stress 
value: [1] 0 1

node_names:  alcohol_consumption 
value: [1] 0 1

node_names:  major_depressive_disorder 
value: [1] 0 1

node_names:  fibroid_tumor 
value: [1] 0 1

node_names:  Fluoxetine 
value: [1] 0 1

node_names:  GIB 
value: [1] 0 1

Datasets:
prozac 
Jun 29, 2016 11:36:27 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Temporal Tiers:  2 
Tier:  0
temporal node:  depressive_symptoms.stress.alcohol_consumption.major_depressive_disorder.Fluoxetine.depressive_disorder.arthralgia.aspirin.antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal.acetaminophen.varicosity.hemorrhoids.fibroid_tumor 
Tier:  1
temporal node:  GIB 
Error in .jcall(fgs_instance, "V", "setHeuristicSpeedup", heuristicSpeedup) : 
  method setHeuristicSpeedup with signature (Ledu/cmu/tetrad/data/IKnowledge;)V not found
> # fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0,samplePrior=1.0, 
> # depth = -1, faithfulness = TRUE, numOfThreads = 6)
> fgs.discrete$parameters #Show the FGS's parameters
Error in fgs.discrete$parameters : 
  object of type 'closure' is not subsettable
> fgs.discrete$datasets #Show the dataset
Error in fgs.discrete$datasets : 
  object of type 'closure' is not subsettable
> fgs.discrete$nodes #Show the result's nodes
Error in fgs.discrete$nodes : object of type 'closure' is not subsettable
> fgs.discrete$edges #Show the result's edges
Error in fgs.discrete$edges : object of type 'closure' is not subsettable
> library(Rgraphviz)
Loading required package: grid
> plot(fgs.discrete$graphNEL, attrs=list(node=list(width = 2, height=4, shape = "ellipse", lwd=500, cex=500, lty=100, fillcolor="white", fontsize=70, fontcolor="darkgreen"), 
+                                        edge=list(color="lightblue", lwd=1),
+                                        graph=list(rankdir="LR"))) 
Error in fgs.discrete$graphNEL : 
  object of type 'closure' is not subsettable

**Comment by kingfish777** [comment]
Thank you for your hard work! In the meantime, I shall work with lib-tetrad-5.3-yzw-cmd.jar for knowledge functionality and relative ease of batch scripting.

**Comment by chirayukong** [comment]
In the FGS Discrete function's priorKnowledge parameter, you should change

priorKnowledge(addtemporal = c("depressive_symptoms stress alcohol_consumption major_depressive_disorder Fluoxetine depressive_disorder arthralgia aspirin antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal acetaminophen varicosity hemorrhoids fibroid_tumor", "GIB")) 

to

priorKnowledge(addtemporal = list(c("depressive_symptoms", "stress alcohol_consumption", "major_depressive_disorder", "Fluoxetine", "depressive_disorder", "arthralgia", "aspirin", "antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal", "acetaminophen", "varicosity", "hemorrhoids", "fibroid_tumor"), c("GIB")))

**Comment by kingfish777** [comment]
Trying now. Takes a few minutes to run. Will report back shortly!

**Comment by chirayukong** [comment]
Btw, thanks for the igraph comments and examples. I'll put it in the README.

**Comment by kingfish777** [comment]
Negatory. Not workin'. 

######################################
Sys.setenv(JAVA_HOME="")
library(rcausal)
prozac <- read.delim("/Users/kingf/prozac/prozac.txt")    #Load the prozac dataset
setwd("/Users/kingf/prozac")
#Compute FGS search
fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0,samplePrior=1.0, 
                             priorKnowledge(addtemporal = list(c("depressive_symptoms", "stress alcohol_consumption", "major_depressive_disorder", "Fluoxetine", "depressive_disorder", "arthralgia", "aspirin", "antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal", "acetaminophen", "varicosity", "hemorrhoids", "fibroid_tumor"), c("GIB"))),
                             depth = -1, numOfThreads = 6)
# fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0,samplePrior=1.0, 
# depth = -1, faithfulness = TRUE, numOfThreads = 6)
fgs.discrete$parameters #Show the FGS's parameters
fgs.discrete$datasets #Show the dataset
fgs.discrete$nodes #Show the result's nodes
fgs.discrete$edges #Show the result's edges
library(Rgraphviz)
plot(fgs.discrete$graphNEL, attrs=list(node=list(width = 2, height=4, shape = "ellipse", lwd=500, cex=500, lty=100, fillcolor="white", fontsize=70, fontcolor="darkgreen"), 
                                       edge=list(color="lightblue", lwd=1),
                                       graph=list(rankdir="LR"))) 
library(igraph)
iprozac <- igraph.from.graphNEL(fgs.discrete$graphNEL) # convert graphNEL to igraph object
plot(iprozac)

#######################

Datasets:
prozac 
Temporal Tiers:  2 
Tier:  0
temporal node:  depressive_symptoms 
temporal node:  stress.alcohol_consumption 
temporal node:  major_depressive_disorder 
temporal node:  Fluoxetine 
temporal node:  depressive_disorder 
temporal node:  arthralgia 
temporal node:  aspirin 
temporal node:  antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal 
temporal node:  acetaminophen 
temporal node:  varicosity 
temporal node:  hemorrhoids 
temporal node:  fibroid_tumor 
Tier:  1
temporal node:  GIB 
Error in .jcall(fgs_instance, "V", "setHeuristicSpeedup", heuristicSpeedup) : 
  method setHeuristicSpeedup with signature (Ledu/cmu/tetrad/data/IKnowledge;)V not found

##########

Looks like it successfully parsed the addTemporal constraints this time, so that is a step in the right direction!

**Comment by chirayukong** [comment]
You need to add "priorKnowledge=" before the priorKnowledge parameter. Without it, the function interprets the parameter from its order, in this case, its order is the heuristicSpeedup's. So the correct calling FGS Discrete should be:

fgs.discrete <- fgs.discrete(df=prozac,structurePrior=1.0, samplePrior=1.0, priorKnowledge = priorKnowledge(addtemporal = list(c("depressive_symptoms", "stress alcohol_consumption", "major_depressive_disorder", "Fluoxetine", "depressive_disorder", "arthralgia", "aspirin", "antiHYPHENinflammatory_agentsCOMMA_nonHYPHENsteroidal", "acetaminophen", "varicosity", "hemorrhoids", "fibroid_tumor"), c("GIB"))), depth = -1, numOfThreads = 6)

**Comment by kingfish777** [comment]
rerunning. will report back as soon as it finishes.

**Comment by kingfish777** [comment]
Reporting back with almost same results. Perhaps forbiddirect and requiredirect are mandatory flags?

Although note that this time, it did get to datasets, further than above, before it died: 


node_names:  depressive_disorder 
value: [1] 0 1

node_names:  depressive_symptoms 
value: [1] 0 1

node_names:  abdominal_pain 
value: [1] 0 1

node_names:  arthralgia 
value: [1] 0 1

node_names:  aspirin 
value: [1] 0 1

node_names:  hemorrhoids 
value: [1] 0 1

node_names:  acetaminophen 
value: [1] 0 1

node_names:  varicosity 
value: [1] 0 1

node_names:  antiHYPHENinflammatory_agentsCOMMA_nonHYPHEN 
value: [1] 0 1

node_names:  stress 
value: [1] 0 1

node_names:  alcohol_consumption 
value: [1] 0 1

node_names:  major_depressive_disorder 
value: [1] 0 1

node_names:  fibroid_tumor 
value: [1] 0 1

node_names:  Fluoxetine 
value: [1] 0 1

node_names:  GIB 
value: [1] 0 1

Datasets:
prozac 
Error in .jcall(fgs_instance, "V", "setHeuristicSpeedup", heuristicSpeedup) : 
  method setHeuristicSpeedup with signature (Z)V not found

**Comment by chirayukong** [comment]
Nope, they are not. The error was the Tetrad jar file doesn't have the setHeuristicSpeedup function (it is not up-to-date). Could you remove the r-causal library and re-install it again?

> detach("package:rcausal", unload=TRUE)
> remove.packages("rcausal")
> library(devtools)
> install_github("bd2kccd/r-causal")

I tried on the r-causal-rstudio docker and it worked.

**Comment by kingfish777** [comment]
Done, and done. Rerunning. WIll report back shortly.

**Comment by kingfish777** [comment]
No cigar as of yet!

**Comment by chirayukong** [comment]
What error did you get? Was it the same one on the setHeuristicSpeedup?

**Comment by kingfish777** [comment]
rerunning on Linux which is working now (without knowledge). Rerunning with knowledge. Will report back in a minute or two.

**Comment by kingfish777** [comment]
waiting for prozac. smaller toy data worked with knowledge. Excellent!!!

**Comment by kingfish777** [comment]
priorKnowledge worked with the larger data set with 2.1M rows. yay.
