### ISSUE TITLE
unused argument (numOfThreads = 2)

### ISSUE THREAD

**Issue by yeqiaoling** [bd2kccd/r-causal#76]
Hi, I followed instruction and installed R library requirements and r-causal. But I couldn't use function "fges" due to following error of "unused argument (numOfThreads = 2)". Could you help me? Thanks! 

> library(rcausal)
> data("charity")   #Load the charity dataset
> fges <- fges(df = charity, penaltydiscount = 2, maxDegree = -1,  faithfulnessAssumed = TRUE, numOfThreads = 2, verbose = TRUE)

> Error in fges(df = charity, penaltydiscount = 2, maxDegree = -1, faithfulnessAssumed = TRUE,  : 
  unused argument (numOfThreads = 2)

**Comment by kingfish777** [comment]
Hi Yeqiaoling: 
To get ages to run, all that you need to do is to remove the numOfThreads flag: 

```
> **library(causal)**
> **data(charity)**
> **fges <- fges(df = charity, penaltydiscount = 2, maxDegree = -1,  faithfulnessAssumed = TRUE, verbose = TRUE)**
Datasets:
charity 

Graph Parameters:
penalty discount =  2 
maxDegree =  -1 
faithfulnessAssumed =  TRUE 
verbose =  TRUE 
Elapsed initializeForwardEdgesFromEmptyGraph = 45 ms
1. INSERT Impact --> Sympathy [] 32.23324736029525  degree = 1 indegree = 1
2. INSERT Impact --> Imaginability [] 11.186154188876003  degree = 2 indegree = 0
3. INSERT Impact --> AmountDonated [] 3.7717900309144383  degree = 3 indegree = 0
```

**Comment by yeqiaoling** [comment]
Thank you kingfish777. I delete the numOfThreads flag and ran into another problem, "Unsupported major.minor version 52.0". I checked other posts and did following things, but still couldn't solve the problem. Can you help? Thanks!

1. updated Java JDK
2. delete rcausal
3. re-install rcausal.

error: 
> fges <- fges(df = charity, penaltydiscount = 2, maxDegree = -1,  faithfulnessAssumed = TRUE, verbose = TRUE)
Error in .jnew("edu/cmu/tetrad/data/ContinuousVariable", nodname) : 
  java.lang.UnsupportedClassVersionError: edu/cmu/tetrad/data/ContinuousVariable : Unsupported major.minor version 52.0

**Comment by kingfish777** [comment]
Is that OS X that you are on? I am familiar with that message. 
I would carry out the following steps and report back: 

1. Uninstall/reinstall the Oracle 8 java JDK (Google on how to do that) --- and make sure that it is Oracle 8, not 9. 
2. remove.packages(c("rJava", "rcausal"), .libPaths())
 also: 
detach_package <- function(pkg, character.only = FALSE)
{
  if(!character.only)
  {
    pkg <- deparse(substitute(pkg))
  }
  search_item <- paste("package", pkg, sep = ":")
  while(search_item %in% search())
  {
    detach(search_item, unload = TRUE, character.only = TRUE)
  }
}
Usage is, for example:

detach_package(rJava)
detach_package(rcausal)
3.) reinstall rJava. I have found that sometimes an archived version of rJava downloaded from CRAN (to be installed locally) will work when the latest release is acting funny.
4.) do the following on command line: 
sudo R CMD javareconf
or if not sudo user:
R CMD javareconf -e
This will configure rJava --- identify where the JDK libraries are located.
5.) next, reinstall r-causal through devtools (using library(devtools); install_github("bd2kccd/r-causal")
Try to boot it up again with library(causal), then running the scripts above.

**Comment by kingfish777** [comment]
What happens when you do one of these? 
sudo R CMD javareconf
or if not sudo user:
R CMD javareconf -e
---------
I'd focus on the rJava procedure outlined above. 
rJava is both the limiting and facilitating factor of r-causal.  ;)

**Comment by yeqiaoling** [comment]
Thank you for your guidelines. I'm working on macOS. I followed procedures and have no problem up to #5 as the JAVA is not found. I also copied terminal outcomes for #4 at the end. Thank you so much for your help! I'm pretty new in Java.

-----------------------------------------------------------------------------------------------------

For #5, the error is 

> library(devtools)
> install_github("bd2kccd/r-causal")
Downloading GitHub repo bd2kccd/r-causal@master
from URL https://api.github.com/repos/bd2kccd/r-causal/zipball/master
Installing rcausal
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/bx/_f2grg5556382x5nck02fl340000gn/T/RtmpDIyPBv/devtools411d43de2022/bd2kccd-r-causal-7c5be55'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘rcausal’ ...
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
JavaVM: requested Java version ((null)) not available. Using Java at "" instead.
JavaVM: Failed to load JVM: /bundle/Libraries/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
Error : .onLoad failed in loadNamespace() for 'rcausal', details:
  call: .jinit()
  error: JNI_GetCreatedJavaVMs returned -1

Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rcausal’
Installation failed: Command failed (1)

-----------------------------------------------------------------------------------------------------

For #4, "sudo R CMD javareconf" outputs are here:
Java interpreter : /usr/bin/java
Java version     : 1.8.0_152
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on macOS

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/../include/darwin -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c conftest.c -o conftest.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.

**Comment by kingfish777** [comment]
jdk1.8.0_162.jdk is working for me --- uninstall the other JDKs and use this one (the .dmg at the bottom) -> 

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by yeqiaoling** [comment]
Thank you kingfish777. It works now!!

**Comment by yeqiaoling** [comment]
Sorry, one more question. So "numOfThreads" flag is no longer used for any dataset?

**Comment by kingfish777** [comment]
numOfThreads flag was for parallelizing fges for larger datasets. I am uncertain of the status of it. No matter, FGES, a score-based structure learning algorithm, is already super fast.

**Comment by yeqiaoling** [comment]
Sounds pretty good! Thanks! (I'll close the issue)

**Comment by chirayukong** [comment]
Thanks @kingfish777 for answering. :-) You are the r-causal expert. We are developing the new version which covers almost algorithms in Tetrad lib. We don't use numOfThreads quite a long time. The fges will determine the number of threads by itself. No need to specify it. The documents are quite outdated.

**Comment by kingfish777** [comment]
@chirayukong 
My pleasure. Will be glad to test the next release when ready. 
Best,
kingfish777
