### ISSUE TITLE
"24 Levels: acoustic_neuroma bells_palsy cochlear_age ... retrocochlear_unknown  Datasets: audiology  Error in .jnew("edu/cmu/tetrad/search/Fgs", score) :    java.lang.NoClassDefFoundError: Could not initialize class edu.cmu.tetrad.util.TetradLogger"

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/r-causal#9]
Library issue? Latest version of rcausal. Maybe tetrad/jar should be in the CLASS_PATH or in libs of JAVA_HOME? 
CentOS v.7
Thanks!
 -Scott

**Comment by chirayukong** [comment]
I think the error said that it can't find the audiology dataset. Also, because the audiology dataset is discrete, you should try it with fgs.discrete.

**Comment by kingfish777** [comment]
Closing issue.

**Comment by kingfish777** [comment]
Closing issue.
